/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_appsync_graphqlEndpoint": "https://h72k3chzlvd6rgyzahbdj4dkte.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-sfmir2cpmbaa5ghplr7tisllc4",
    "API": {
        "GraphQL": {
            "endpoint": "https://h72k3chzlvd6rgyzahbdj4dkte.appsync-api.ap-southeast-2.amazonaws.com/graphql",
            "region": "ap-southeast-2",
            "defaultAuthMode": "apiKey",
            "apiKey": "da2-sfmir2cpmbaa5ghplr7tisllc4"
        }
    }
};


export default awsmobile;
